### ISSUE TITLE
Keep alive interval issue

### ISSUE THREAD

**Issue by amitguptaRean** [awslabs/aws-iot-device-sdk-cpp-v2#10]
We set the keep alive interval for both socket and mqtt connection to 30s
Reason - When a device looses WiFi we want a disconnected lifecycle event as quickly as possible
But we still see connection getting disconnected around 45s.

In previous AWS C SDK 3.1 - the SDK used to send periodic pings to keep the connection alive forever.

**Question 1)** Has this been removed in aws-iot-device-sdk-cpp-v2 ?

**Question 2)** Does our client code need to send periodic pings if we are not publishing anything within keep alive interval ?

```
if (!mqttConnection->Connect(clientId.c_str(), false, 30))
	{
		fprintf(stderr, "MQTT Connection failed with error %s\n", ErrorDebugString(mqttConnection->LastError()));
		return FAILURE_CONNECT;
	}
```

**Comment by justinboswell** [comment]
You are correct. We have not implemented the heartbeat/periodic ping feature from Paho that the previous SDK used to maintain the connection, but we do have this on our roadmap for the near future. We do send the keepalive value to the IoT service, which will then use it as a timeout. That said, your MqttConnection should reconnect every time it's dropped unless network conditions prevent it from doing so.

In order to facilitate a quick handoff between WiFi and cellular, I would recommend experimenting with keepalive values in the 5-10s range, and send a ping at about 1.5-2x that frequency (to account for latency/imprecise timing). Once we add the keepalive pings internally, you can remove this behavior.

**Comment by JonathanHenson** [comment]
One more note: the keep alive value you’re setting here is tcp keep alive, not the mqtt Ping frequency. In reality that will tell you when the socket is disconnected and keep the socket alive assuming the value is set low enough.

**Comment by ravichandhraRean** [comment]
@JonathanHenson 

```
if (!mqttConnection->Connect(clientId.c_str(), false, 30))
	{
		fprintf(stderr, "MQTT Connection failed with error %s\n", ErrorDebugString(mqttConnection->LastError()));
		return FAILURE_CONNECT;
	}
```

the 30 sec passed in the above method is using to connect to IoT broker along with socketOptions, means is this mqtt keep-alive or not?

```
bool MqttConnection::Connect(const char *clientId, bool cleanSession, uint16_t keepAliveTime) noexcept
            {
                ByteBuf clientIdBuf = aws_byte_buf_from_c_str(clientId);
                ByteCursor clientIdCur = aws_byte_cursor_from_buf(&clientIdBuf);

                ByteCursor hostNameCur = aws_byte_cursor_from_buf(&m_hostNameBuf);
                aws_tls_connection_options *tlsOptions = m_useTls ? &m_tlsOptions : nullptr;
                if (aws_mqtt_client_connection_connect(
                        m_underlyingConnection,
                        &hostNameCur,
                        m_port,
                        &m_socketOptions,
                        tlsOptions,
                        &clientIdCur,
                        cleanSession,
                        keepAliveTime,
                        MqttConnection::s_onConnectionCompleted,
                        this))
                {
                    return false;
                }

                m_connectionState = ConnectionState::Connecting;
                return true;
            }
```

**Comment by JonathanHenson** [comment]
Keep alive on socket options only applies to tcp keep alive, not mqtt. We’re adding that soon. In the meantime you can schedule a task to send a ping at the interval you specify with the mqtt connection.

**Comment by graebm** [comment]
Just FYI for anyone who finds this old ticket, automatic keepalive via PING was implemented in late March 2019:
https://github.com/awslabs/aws-c-mqtt/pull/58
