### ISSUE TITLE
Real-Time publish support

### ISSUE THREAD

**Issue by ravichandhraRean** [awslabs/aws-iot-device-sdk-cpp-v2#12]
Hi,

Can we publish to multiple topics in real-time using this sdk?

means publish to different topics without any delay.

Can we do shadow operations and topics pub-sub in real-time , means without any delays?

Note: We want to use single mqtt client only. Using multiple clients(with different client ids) we can achieve this but we don't want to do this.

Thank you

Regards,
Ravichandhra Palla
Hitachi Vantara
ravichandhra.palla@hitachivantara.com

**Comment by justinboswell** [comment]
You can publish to as many topics as you want, at whatever frequency you want, within the [limits of the IoT Core](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot) service. Can you be more specific about what you mean by real-time here?

The publish speed would be more limited by the IoT Core limits on throughput and the latency of getting a message across the internet than by the library. Each publish is completed asynchronously, so your application code can fire publishes at the library as fast as it can produce them.

There are no limits on how many different topics you could be publishing or subscribing to simultaneously within the client library. If you are connecting to the IoT Core service, then all limits will be enforced by the service.

**Comment by ravichandhraRean** [comment]
Hi @justinboswell 

thank you.

Can you be more specific about what you mean by real-time here?
1. means publishing to two different topics parallel (using two threads) , in this will there be any delay in any one publish 
2. at the same time we are receiving delta and reporting back using another thread

**Comment by JonathanHenson** [comment]
I’m confused about the threads stuff. Everything is running on non-blocking io, there’s no need for threads to do any of this. It will all be processed in real-time.  

Unless you have more than 100 or so connections I’d recommend only using 1 thread for your event loop group.
