### ISSUE TITLE
Abnormal MQTT Client Connection behavior with intermittent network connection

### ISSUE THREAD

**Issue by ravichandhraRean** [awslabs/aws-iot-device-sdk-cpp-v2#15]
Hi,

We found these issues when network lost and resumed,

**After network lost**

1. Disconnect message published to IoT topic after keep-alive expiration (ourcase: 30 x 1.5 = 45 sec)
2. but the OnDisconnect/OnInterrupt  handlers not triggering 
3. After disconnected message published also , Ping: mqttConnection->Ping() is working and 
connection-state: mqttConnection->GetConnectionState() is also 2(means connected)

**After network resumed** 

1. after getting network(with in keepalive) Onresume handler not triggering
2. If network lost and get immediately then only the connection is alive otherwise disconnect message published to IoT topic

Thank you.

Regards,
Ravichandhra Palla
Hitachi Vantara
ravichandhra.palla@hitachivantara.com

**Comment by ravichandhraRean** [comment]
Normal behaviour should be(correct me if i am understanding it in wrong way),

**1.	After network lost**
a.	Disconnect message should publish to IoT topic after keep-alive expiration (30 x 1.5 = 45 sec)
b.	OnInterrupt  handler should triggered
c.	mqttConnection->GetConnectionState() should return attempting/connecting state, mqttConnection->Ping() should return error

**2.	After network resumed(within keep-alive expiration)**
a.	Onresume handler should triggered
b.	mqttConnection->GetConnectionState() should return connected state, mqttConnection->Ping() should return success

**3.	After network resumed(after keep-alive expiration)**
a.	Disconnect message should publish to IoT topic after keep-alive expiration (30 x 1.5 = 45 sec)
b.	OnDisconnect handler should triggered
c.	mqttConnection->GetConnectionState() should return disconnected state, mqttConnection->Ping() should return error

Thank you.

Regards,
Ravichandhra Palla
Hitachi Vantara
ravichandhra.palla@hitachivantara.com

**Comment by ravichandhraRean** [comment]
Hi,

We have gone through the mqttConnection->Ping() source code and is there any reason for this,

MqttClient.cpp
`void MqttConnection::Ping() { aws_mqtt_client_connection_ping(m_underlyingConnection); }`

client.c
```
int aws_mqtt_client_connection_ping(struct aws_mqtt_client_connection *connection) {

    mqtt_create_request(connection, &s_pingreq_send, connection, NULL, NULL);

    return AWS_OP_SUCCESS;
}
```

client_impl.h (implemented in client_channel_handler.c)
```
/* This function registers a new outstanding request, calls send_request
 and returns the message identifier to use (or 0 on error). */
AWS_MQTT_API uint16_t mqtt_create_request(
    struct aws_mqtt_client_connection *connection,
    aws_mqtt_send_request_fn *send_request,
    void *send_request_ud,
    aws_mqtt_op_complete_fn *on_complete,
    void *on_complete_ud);
```

1. Why the MqttConnection::Ping() is void even though aws_mqtt_client_connection_ping returning an int value
2. Why aws_mqtt_client_connection_ping(m_underlyingConnection) always returning AWS_OP_SUCCESS

Thank you.

Regards,
Ravichandhra Palla
Hitachi Vantara
ravichandhra.palla@hitachivantara.com

**Comment by JonathanHenson** [comment]
These fixes are already in process. They should be available in the next few days.

https://github.com/awslabs/aws-c-mqtt/pull/58

https://github.com/awslabs/aws-c-io/pull/112

**Comment by ravichandhraRean** [comment]
Hi @JonathanHenson,

Thank you. We are waiting for these fixes.

**Comment by JonathanHenson** [comment]
okay, we finally have a branch and PR on the CRT you can try out:
https://github.com/awslabs/aws-crt-cpp/pull/13

**Comment by JonathanHenson** [comment]
In this change, PINGs are automatic. If you decide to use keep alive, you can drop the ping frequency to the absolutely minimum (just use the defaults) and then rely on tcp keep alive to tell you when the connection drops. However, even if you wanted to use pings for this, simply set the mqtt keep alive value as you want it, and we'll handle it all for you.

**Comment by graebm** [comment]
The latest tagged version of aws-crt-cpp "v0.1.4" has the changes described above by Jonathan

**Comment by ravichandhraRean** [comment]
Hi @JonathanHenson , @graebm ,

Thank you.

1. Now the automatic Ping is working

But we are facing new Issues when network resumed,

we are using mqtt keep-alive = 30 seconds

1. network resumed before keep-alive expired - it is detecting network(after some seconds)  and triggered OnResume handler and immediately getting a segmentation fault

2. network resumed after keep-alive expired - it is detecting network(after some seconds) and triggered OnResume handler and immediately getting a segmentation fault


Thank you.

Regards,
Ravichandhra Palla
Hitachi Vantara
ravichandhra.palla@hitachivantara.com

**Comment by JonathanHenson** [comment]
I’ve run this path a lot recently, so this is somewhat surprising, could you provide a stack trace?

**Comment by JonathanHenson** [comment]
This WOULD happen if for some reason aws-c-io didn’t get updated for some reason

**Comment by JonathanHenson** [comment]
In the meantime I’ll try to repel today

**Comment by JonathanHenson** [comment]
somehow these emails got mixed up in my inbox so I'll respond to each here:

1.) I need a stack trace on this, I'm having trouble reporoducint this one.
2.) I think this is the same as 1.)
3.) I don't think you actually want what you're asking for here. If your keep alive expires, the ideal behavior is to keep trying to reconnect until your network comes back. Disconnected state is only entered if you explicitly call "Disconnect()". Could you provide me more details as to why you want different behavior?

**Comment by ravichandhraRean** [comment]
Hi @JonathanHenson ,

Thank you, for your reply.

I will test this one more time and provide the stack trace for 1.) and 2.)

I got the answer the for 3.) here, #16 (Now it's cleared for me and I asked my further query there only, I will not mix that here).

Thank you.

Regards,
Ravichandhra Palla

**Comment by ravichandhraRean** [comment]
Hi @JonathanHenson ,

Output trace:

```
Thread 2 "app.out" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x75c8a3d0 (LWP 1819)]
0x76dca300 in mqtt_request_complete () from /home/pi/projects/libs/lib/libaws-c-mqtt.so.0unstable
Segmentation fault

[Switching to thread 19 (Thread 0x752ff3d0 (LWP 1943))](running)
=thread-selected,id="19"
[Thread 0x752ff3d0 (LWP 1943) exited]
The thread 'app.out' (0x797) has exited with code 0 (0x0).
[Thread 0x713ff3d0 (LWP 1831) exited]
[Thread 0x725ff3d0 (LWP 1829) exited]
The thread 'app.out' (0x727) has exited with code 0 (0x0).
The thread 'app.out' (0x725) has exited with code 0 (0x0).
[Thread 0x72dff3d0 (LWP 1828) exited]
The thread 'app.out' (0x724) has exited with code 0 (0x0).
[Thread 0x738ff3d0 (LWP 1827) exited]
The thread 'app.out' (0x723) has exited with code 0 (0x0).
[Thread 0x740ff3d0 (LWP 1826) exited]
[Thread 0x748ff3d0 (LWP 1825) exited]
[Thread 0x75c8a3d0 (LWP 1819) exited]
The thread 'app.out' (0x722) has exited with code 0 (0x0).
The thread 'app.out' (0x721) has exited with code 0 (0x0).
The thread 'app.out' (0x71b) has exited with code 0 (0x0).

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
The thread 'app.out' (0x718) has exited with code 0 (0x0).
The program '' has exited with code 0 (0x0).
```

**Comment by amitguptaRean** [comment]
This is now fixed on the aws crt connection_manager branch
