### ISSUE TITLE
Getting connected state even though disconnect message published to IoT topic

### ISSUE THREAD

**Issue by ravichandhraRean** [awslabs/aws-iot-device-sdk-cpp-v2#16]
Hi,

to check the state of MQTT Client connection we are making this call for every 10 seconds,
`int connectionState = static_cast<int>(mqttConnection->GetConnectionState()`

but it is returning 2 - means connected, even though there is no network connected and disconnected message published to IoT life-cycle topic

MqttClient.h
`inline ConnectionState GetConnectionState() const noexcept { return m_connectionState; }`

is the m_connectionState is updating it's value when connection interrupted/disconnected/resumed?

Thank you.

Regards,
Ravichandhra Palla
Hitachi Vantara
ravichandhra.palla@hitachivantara.com

**Comment by graebm** [comment]
This should be fixed if you update `https://github.com/awslabs/aws-crt-cpp.git` to version `v0.1.4`

**Comment by ravichandhraRean** [comment]
Hi @graebm,

Thank you. I tested the new update and here are my findings,

`int connectionState = static_cast<int>(mqttConnection->GetConnectionState()`

1. After network loss OnInterrupted handler triggered and this method **returning 1 (Connecting)**
2. after keep-alive expiration a disconnect message published to IoT lifecycle topic but OnDisconnect Handler not triggered and this method still returning 1 (Connecting) but it should return 3 (Disconnected)

please reopen this issue

Thank you.

Regards,
Ravichandhra Palla
Hitachi Vantara
ravichandhra.palla@hitachivantara.com

**Comment by JonathanHenson** [comment]
Why do you want it to show disconnected(), don’t you want it to be reconnecting when it’s offline?

**Comment by graebm** [comment]
@ravichandhraRean The MQTT client automatically attempts to reconnect unless the user has explicitly called `.Disconnect()`. So, as you observed, if the client loses its connection due to keepalive, OnConnectionInterrupted will trigger and the client will be in the `Connecting` state. It is still safe to interact with the client. Publish and Subscribe operations are queued, and will be sent to the server once a connection is re-established.

**Comment by ravichandhraRean** [comment]
@JonathanHenson  and @graebm ,

Thank you, now I understand that the MQTT client automatically attempts to reconnect , in this case we don't need to show any disconnected() state.

1.  But will it try for reconnect till the network resumed and automatically resubscribe for all subscriptions or is there any time limit for this?

Thank you.

Regards,
Ravichandhra Palla

**Comment by JonathanHenson** [comment]
No time limit, and assuming you are using dirty sessions your subscriptions will remain.

**Comment by ravichandhraRean** [comment]
@JonathanHenson ,

Thank you for clarifying this.
