### ISSUE TITLE
cmake build failure

### ISSUE THREAD

**Issue by amitguptaRean** [awslabs/aws-iot-device-sdk-cpp-v2#20]
Changes in the API is not reflected in sample programs
Refer to 
\aws_sdk\aws-iot-device-sdk-cpp-v2\samples\jobs\describe_job_execution\main.cpp
Line# 163 fails build
**Io::ClientBootstrap bootstrap(eventLoopGroup);**

Severity	Code	Description	Project	File	Line	Suppression State
Error		no matching function for call to ‘Aws::Crt::Io::ClientBootstrap::ClientBootstrap(Aws::Crt::Io::EventLoopGroup&)’	C:\appdev\src\deviceagentcpp\aws_sdk\aws-iot-device-sdk-cpp-v2\CMakeLists.txt	C:\appdev\src\deviceagentcpp\aws_sdk\aws-iot-device-sdk-cpp-v2\samples\jobs\describe_job_execution\main.cpp	163	

aws_sdk\aws-iot-device-sdk-cpp-v2\samples\shadow\shadow_sync\main.cpp
Line# 203 fails build

Please reflect the new api changes to samples.

**Comment by ColdenCullen** [comment]
This seems like as good a time as any to finally get our CI setup on this repo... We'll get working on it.

**Comment by JonathanHenson** [comment]
I just pushed a PR that handles this.

**Comment by amitguptaRean** [comment]
Thanks, this is fixed now in master
