### ISSUE TITLE
Publish fail after loss of connection/wifi

### ISSUE THREAD

**Issue by amitguptaRean** [awslabs/aws-iot-device-sdk-cpp-v2#22]
Hi

We have an MQTT agent running on debian linux that publishes data to Greengrass core topic. 
We have observed that the publish method does not works if the device looses ethernet connection /wifi and then regains the connection.
After the wifi/ethernet connectivity is back, why does the publish not work ?
Our mqtt connection is a single connection that we construct throughout the lifetime of the agent , and we expect that after each cycle of onInterrupt/OnResume the publish should work.

Thanks
Amit Gupta

**Comment by JonathanHenson** [comment]
Well greengrass core is qos 0, so there’s no guarantee the message will be sent. We could look at adding offline queueing here, but it wouldn’t be spec compliant.

**Comment by amitguptaRean** [comment]
We do not want to queue the data
But the publish should work once the Ethernet/Wi-Fi resumes .

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JonathanHenson** [comment]
Ah, got it. I’ll track this down and get a fix out.

**Comment by ravichandhraRean** [comment]
Hi @JonathanHenson ,

Any update on this.

Thank you.

**Comment by amitguptaRean** [comment]
Publish is definitely not working after a connection is Resumed.

**Comment by amitguptaRean** [comment]
Once the callbacks were made lightweight (return immediately, and not call another AWS SDK method within the callback) this issues gets resolved
