### ISSUE TITLE
Deterministic segmentation  fault - ByteBufDelete

### ISSUE THREAD

**Issue by amitguptaRean** [awslabs/aws-iot-device-sdk-cpp-v2#26]
**Segmentation fault highlighted**

int CAwsSdkInterface::publish_async(const char *topic, uint8_t *buffer, size_t length) {
	//for unit tests workflow
	int rc = get_connection();
	if (rc != SUCCESS) {
		return rc;
	}
	ByteBuf payload = ByteBufNewCopy(DefaultAllocator(), buffer, length);
	/*
	* This will be invoked upon the completion of Publish
	*/
	auto onOpComplete = [&payload](Mqtt::MqttConnection& conn, uint16_t packetId, int errorCode)
	{
		if (errorCode == AWS_OP_SUCCESS) {
			spdlog::debug("Publish Operation on packetId {0} Succeeded", (int)packetId);
		}
		else {
			spdlog::error("Publish Operation failed with error {0}", aws_error_debug_str(errorCode));
		}
		**ByteBufDelete(payload);**
	};
	/*
	 * Publish our message.
	 */
	auto packetId = mqttConnection->Publish(topic, pubSubQos, false, payload, std::move(onOpComplete));
		(void)packetId;

	return SUCCESS;
}

**Comment by JonathanHenson** [comment]
In your capture, publish is asynchronous. That reference isn’t valid. You need to capture by value.

**Comment by amitguptaRean** [comment]
Thanks ... this one is working. My bad .
