### ISSUE TITLE
CMake build Error with VS2019 : error D8016: '/O2' and '/RTC1' command-line options are incompatible 

### ISSUE THREAD

**Issue by avrahams** [awslabs/aws-iot-device-sdk-cpp-v2#27]
CMake build with VS 2019 endes with error

**cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible** 

`C:\Users\AvrahamShalev1\Documents\REUnderstand\aws-crt-cpp-build>cmake -DCMAKE_INSTALL_PREFIX="C:/Users/AvrahamShalev1/Documents/REUnderstand/AWS" -DCMAKE_PREFIX_PATH="C:/Users/AvrahamShalev1/Documents/REUnderstand/AWS" -DBUILD_SHARED_LIBS=ON -DBUILD_DEPS=ON ../aws-crt-cpp
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.21.27702.2
-- The CXX compiler identification is MSVC 19.21.27702.2
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
install dir C:/Users/AvrahamShalev1/Documents/REUnderstand/AWS
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/AvrahamShalev1/Documents/REUnderstand/aws-crt-cpp-build/deps
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  CMake does not need to re-run because C:/Users/AvrahamShalev1/Documents/REUnderstand/aws-crt-cpp-build/deps/CMakeFiles/generate.stamp is up-to-date.
  Creating directories for 'AwsCCommon'
  Building Custom Rule C:/Users/AvrahamShalev1/Documents/REUnderstand/aws-crt-cpp/aws-common-runtime/CMakeLists.txt
  CMake does not need to re-run because C:/Users/AvrahamShalev1/Documents/REUnderstand/aws-crt-cpp-build/deps/CMakeFiles/generate.stamp is up-to-date.
  Performing download step (git clone) for 'AwsCCommon'
  Cloning into 'AwsCCommon'...
  Note: checking out 'v0.3.6'.

  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by performing another checkout.

  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -b with the checkout command again. Example:

    git checkout -b <new-branch-name>

  HEAD is now at cbe96ad Faster CBMC stubs for memset and memcpy (#300)
  No update step for 'AwsCCommon'
  No patch step for 'AwsCCommon'
  Performing configure step for 'AwsCCommon'
  -- The C compiler identification is MSVC 19.21.27702.2
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.21.27702/bin/Hostx64/x64/cl.exe -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
  -- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Failed
  -- Performing Test AWS_HAVE_MSVC_MULX
  -- Performing Test AWS_HAVE_MSVC_MULX - Failed
  -- Performing Test AWS_HAVE_GCC_INLINE_ASM
  -- Performing Test AWS_HAVE_GCC_INLINE_ASM - Failed
  -- Performing Test HAVE_M_AVX2_FLAG
  -- Performing Test HAVE_M_AVX2_FLAG - Success
  -- Performing Test HAVE_AVX2_INTRINSICS
  -- Performing Test HAVE_AVX2_INTRINSICS - Success
  -- Performing Test HAVE_MM256_EXTRACT_EPI64
  -- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
  -- Performing Test HAVE_MAY_I_USE
  -- Performing Test HAVE_MAY_I_USE - Failed
  -- Performing Test HAVE_BUILTIN_CPU_SUPPORTS
  -- Performing Test HAVE_BUILTIN_CPU_SUPPORTS - Failed
  -- Performing Test HAVE_MSVC_CPUIDEX
  -- Performing Test HAVE_MSVC_CPUIDEX - Success
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stdbool.h
  -- Looking for stdbool.h - found
  -- Performing Test HAS_WGNU
  -- Performing Test HAS_WGNU - Failed
  -- Performing Test HAVE_SYSCONF
  -- Performing Test HAVE_SYSCONF - Failed
  -- Building SIMD base64 decoder
  -- Packaging is only supported on Linux
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/Users/AvrahamShalev1/Documents/REUnderstand/aws-crt-cpp-build/deps/build/src/AwsCCommon-build
  Performing build step for 'AwsCCommon'
  Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
  Copyright (C) Microsoft Corporation. All rights reserved.

    Checking Build System
    CMake does not need to re-run because C:/Users/AvrahamShalev1/Documents/REUnderstand/aws-crt-cpp-build/deps/build/src/AwsCCommon-build/CMakeFiles/generate.stamp is up-to-date.
    CMake does not need to re-run because C:/Users/AvrahamShalev1/Documents/REUnderstand/aws-crt-cpp-build/deps/build/src/AwsCCommon-build/tests/CMakeFiles/generate.stamp is up-to-date.
    Building Custom Rule C:/Users/AvrahamShalev1/Documents/REUnderstand/aws-crt-cpp-build/deps/build/src/AwsCCommon/CMakeLists.txt
    CMake does not need to re-run because C:/Users/AvrahamShalev1/Documents/REUnderstand/aws-crt-cpp-build/deps/build/src/AwsCCommon-build/CMakeFiles/generate.stamp is up-to-date.
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [C:\Users\AvrahamShalev1\Documents\REUnderstand\aws-crt-cpp-build\deps\AwsCCommon.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(429,5): error MSB6006: "CL.exe" exited with code 2. [C:\Users\AvrahamShalev1\Documents\REUnderstand\aws-crt-cpp-build\deps\build\src\AwsCCommon-build\aws-c-common.vcxproj] [C:\Users\AvrahamShalev1\Documents\REUnderstand\aws-crt-cpp-build\deps\AwsCCommon.vcxproj]
CMake Error at CMakeLists.txt:80 (message):
  Failed to build aws crt libraries.

-- Configuring incomplete, errors occurred!

**Comment by justinboswell** [comment]
Thanks for the report, this is helpful! We have not yet tried VS 2019. We intend to in the near future, but it's not yet something we test on. You'll see it in the release notes when we push a VS 2019-ready version.

**Comment by AndreyPlotkinOr** [comment]
Following SO, you can try this answer: https://stackoverflow.com/a/44416270/1100913
It helped to resolve the problem.
