### ISSUE TITLE
Some questions about the API capabilities

### ISSUE THREAD

**Issue by David-Haim** [awslabs/aws-iot-device-sdk-cpp-v2#34]
Hello there, AWS-IOT team, keep up the great work!

In my team, we (plan) on using this version of the API after we've dabbled with the old C-API.
We're having a few misunderstanding regarding what the this API is capable of:

1) In the pub-sub capabilities, in the old C API, you yield in order to receive messages you subscribed to their topic, but you can't do anything in the meanwhile. while you're yielding, you can't subscribe to new topics nor request/delete the device shadow.

This API works with websockets and works a bit differently : in this API - can you listen to new messages while being able to do other things? it's unclear to us. Ideally, we would like to receive messages in the background (by leaving a callback for the new message) and be able to publish messages, manipulate device shadow, etc.

2) Device shadow: is there a "push" notification for device shadow messages? Ideally, we would like our mobile app to update the device shadow, and other mobile apps, who are logged to the same user will receive a notification that the device shadow was updated/deleted and react/show the new update data.

the closest thing to what we want is the delta callback - when you update the device shadow the server returns a delta JSON to the SDK. but from my understanding, this callback is invoked by the updating SDK and not "globally". 

does this new C++ API provides the capabilities of achieving what I described above? if not, is there a way to implement the above in this API?

thanks!

**Comment by JonathanHenson** [comment]
1. Everything is non-blocking so if I understand your question correctly. Yes you can do whatever you need to do and you’ll receive callbacks when something happens.

2. We haven’t added push notification support yet, but feel free to add it in aws-crt-cpp if you’d like!

**Comment by David-Haim** [comment]
thanks! 

any prediction as for when this API becomes production ready?
