### ISSUE TITLE
AWS SDK Build failure

### ISSUE THREAD

**Issue by amitguptaRean** [awslabs/aws-iot-device-sdk-cpp-v2#35]
Hi
We took latest code from AWS SDK CPP V2 today and it fails to build.
Please help urgently as we are stuck testing and taking forward some critical issues pending for our project.

/home/agupta/deviceagentcpp-bin/lib/libaws-c-http.a(hpack.c.o): In function `aws_hpack_context_new':
hpack.c:(.text+0xd3a): undefined reference to `aws_huffman_encoder_init'
hpack.c:(.text+0xd44): undefined reference to `aws_huffman_decoder_init'
/home/agupta/deviceagentcpp-bin/lib/libaws-c-http.a(hpack.c.o): In function `aws_hpack_encode_string':
hpack.c:(.text+0x1062): undefined reference to `aws_huffman_encode'
collect2: error: ld returned 1 exit status
iot_layer/tests/CMakeFiles/test-iot_layer.dir/build.make:137: recipe for target 'iot_layer/tests/test-iot_layer' failed
make[2]: *** [iot_layer/tests/test-iot_layer] Error 1
CMakeFiles/Makefile2:1727: recipe for target 'iot_layer/tests/CMakeFiles/test-iot_layer.dir/all' failed
make[1]: *** [iot_layer/tests/CMakeFiles/test-iot_layer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Thanks
Amit Gupta

**Comment by graebm** [comment]
Delete your aws-crt-cpp's build directory and try again.
aws-crt-cpp has known issues when rebuilding after pulling an updated version

**Comment by graebm** [comment]
The incoming "continuous integration" PR: https://github.com/awslabs/aws-iot-device-sdk-cpp-v2/pull/36
will add a sanity check that what's in master ought to build.

**Comment by Kevin-Tacheny** [comment]
We always do a clean build.  
If we roll back the commits in our cmake using 
GIT_TAG 792a4b for aws-crt-cpp 
and 
GIT_TAG ba362f for aws-iot-device-sdk-cpp-v2
We do not see the linker issue with aws-c-http not finding aws-c-compression
I see the command line for the link step has the proper library include in the proper spot.

**Comment by amitguptaRean** [comment]
I did a clean  build once more assuming something was checked in last night.
libaws-c-http.a(hpack.c) definitely missing reference to **`aws_huffman_encoder_init'**
Could you verify if you guys introduced these methods in your source code but did not add it to the linkage ?
============================================
Scanning dependencies of target test-iot_layer
[ 72%] Building CXX object iot_layer/tests/CMakeFiles/test-iot_layer.dir/src/test_CAwsSdkInterface.cpp.o
[ 73%] Building CXX object iot_layer/tests/CMakeFiles/test-iot_layer.dir/src/main.cpp.o
**[ 75%] Linking CXX executable test-iot_layer
/home/agupta/deviceagentcpp-bin/lib/libaws-c-http.a(hpack.c.o): In function `aws_hpack_context_new':
hpack.c:(.text+0xd3a): undefined reference to `aws_huffman_encoder_init'
hpack.c:(.text+0xd44): undefined reference to `aws_huffman_decoder_init'
/home/agupta/deviceagentcpp-bin/lib/libaws-c-http.a(hpack.c.o): In function `aws_hpack_encode_string':
hpack.c:(.text+0x1062): undefined reference to `aws_huffman_encode'
collect2: error: ld returned 1 exit status**
iot_layer/tests/CMakeFiles/test-iot_layer.dir/build.make:137: recipe for target 'iot_layer/tests/test-iot_layer' failed
make[2]: *** [iot_layer/tests/test-iot_layer] Error 1
CMakeFiles/Makefile2:1727: recipe for target 'iot_layer/tests/CMakeFiles/test-iot_layer.dir/all' failed
make[1]: *** [iot_layer/tests/CMakeFiles/test-iot_layer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by amitguptaRean** [comment]
Seems all we had to do was to include the following library to our cmake
**aws-c-compression.a**
This is a new library that was added by CRT team recently.

**Comment by ravichandhraRean** [comment]
Hi,

Still we didn't understand why we need to link all those internal libs need by aws-crt-cpp

Thank you.

**Comment by JonathanHenson** [comment]
99% chance we forgot to add find_dependency(aws-c-compression) to the aws-c-http cmake config proxy file.

**Comment by ravichandhraRean** [comment]
Thanks for the reply @JonathanHenson , it will really help us if there is small description/doc available to how to use aws-crt-cpp and aws-iot-device-sdk-cpp-v2 static and dynamic libs with a CMAKE build.

My assumption are,
1. Build both aws-crt-cpp and aws-iot-device-sdk-cpp-v2 (either static libs / dynamic libs)
2. In our project CMAKE file link those libaws-crt-cpp.so/.a and libIotShadow-cpp.so/.a (Jobs and Discovery if needed)
3. we should able to build our project executable without linking any other internal libs needed by either aws-crt-cpp / shadow lib

Thank you.

Thank you.

**Comment by JonathanHenson** [comment]
Your assumptions are fine, I’m saying we probably have a cmake miss on our side that we can fix quickly (one liner)

**Comment by ravichandhraRean** [comment]
Thanks for the confirmation @JonathanHenson , But If we didn't add the internal libs we are getting compilation error so here i am posting our CMakeLists.txt can you suggest any modifications to it.

```cmake
cmake_minimum_required(VERSION 3.5 FATAL_ERROR)
project(iot_layer VERSION 0.1 LANGUAGES CXX)
include(GNUInstallDirs)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

enable_testing() 

# -- iot_layer ----------------------------------------------------------
add_library(${PROJECT_NAME} 
    ./src/CAwsSdkInterface.cpp
    # Example for GoogleTest for understanding, will be remove in Sprint#3
    ./src/division.cpp
)

target_include_directories(${PROJECT_NAME}
    PRIVATE
        ./include
    PUBLIC
        ./include
)

target_link_libraries(${PROJECT_NAME} 
    spdlog
    iot_layer_interface 
    IotJobs-cpp_LIB
    IotShadow-cpp_LIB
    device_db 
    aws-crt-cpp_LIB
    aws-c-cal_LIB
    aws-c-mqtt_LIB
    aws-c-io_LIB
    aws-c-common_LIB
    s2n_LIB
    aws-c-http_LIB
    aws-c-compression_LIB
    crypto
    pthread
)

add_subdirectory(tests)

# Installation  
install (
    FILES 
        ./${PROJECT_NAME}/include/CAwsSdkInterface.h
        ./${PROJECT_NAME}/include/division.h
    TARGETS 
        ${PROJECT_NAME} 
    DESTINATION 
        lib/${PROJECT_NAME}
)
```

Thank you.

**Comment by justinboswell** [comment]
Where are all the aws-c*-*_LIB variables coming from? I don't see any calls to ```find_package()```? Did you pass them in on the command line? 

If you're using ```find_package()```, you should be able to just link ```AWS::aws-crt-cpp```, and the rest of the libraries should end up linked transitively. This is how all the other language CRTs do their linking ([example](https://github.com/awslabs/aws-crt-dotnet/blob/master/native/CMakeLists.txt#L136)).

**Comment by ravichandhraRean** [comment]
Hi @justinboswell ,

**Where are all the aws-c*-*_LIB variables coming from? I don't see any calls to find_package()? Did you pass them in on the command line?**

Ans: We are importing aws sdk libs with that extra _LIB name and we are using them here. I copied the cmake script how we are building the aws-sdk libs
```
FOREACH(LIB ${AWS_LIBS})
    add_library(${LIB}_LIB STATIC IMPORTED)
    set_target_properties(${LIB}_LIB PROPERTIES IMPORTED_LOCATION "${CMAKE_INSTALL_PREFIX}/lib/lib${LIB}.a")
ENDFOREACH(LIB)
```

Script using to build and load aws-sdk-libs
```
if("${pt_project}" STREQUAL "external")
    ExternalProject_Add(aws-crt-cpp
        GIT_REPOSITORY https://github.com/awslabs/aws-crt-cpp.git
        # TODO: Remove flag “BUILD_SHARED_LIBS=OFF” as this will be provided while executing the top-most/root CMake file.
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX} -DBUILD_SHARED_LIBS=OFF -DBUILD_DEPS=ON
        # Hack to download pillowtalk at the very beginning. This is necessary for gitlab being a private repo which requires authentication.
        DEPENDS pt_lib
    )
else()
    ExternalProject_Add(aws-crt-cpp
        GIT_REPOSITORY https://github.com/awslabs/aws-crt-cpp.git
        # TODO: Remove flag “BUILD_SHARED_LIBS=OFF” as this will be provided while executing the top-most/root CMake file.
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX} -DBUILD_SHARED_LIBS=OFF -DBUILD_DEPS=ON
    )
endif()

ExternalProject_Add(aws-iot-device-sdk-cpp-v2
    GIT_REPOSITORY https://github.com/awslabs/aws-iot-device-sdk-cpp-v2.git
    # TODO: Remove flag “BUILD_SHARED_LIBS=OFF” as this will be provided while executing the top-most/root CMake file.
    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX} -DBUILD_SHARED_LIBS=OFF -DBUILD_DEPS=ON
    DEPENDS aws-crt-cpp
)

set(AWS_LIBS
        aws-c-io
        aws-c-mqtt
        aws-c-common
        aws-c-cal
        IotJobs-cpp
        IotShadow-cpp
        s2n
        aws-crt-cpp
        aws-c-http
		aws-c-compression
)

FOREACH(LIB ${AWS_LIBS})
    add_library(${LIB}_LIB STATIC IMPORTED)
    set_target_properties(${LIB}_LIB PROPERTIES IMPORTED_LOCATION "${CMAKE_INSTALL_PREFIX}/lib/lib${LIB}.a")
ENDFOREACH(LIB)

```
