### ISSUE TITLE
How to construct UpdateShadowRequest  from json string

### ISSUE THREAD

**Issue by amitguptaRean** [awslabs/aws-iot-device-sdk-cpp-v2#40]
Please refer to update_digital_twin method we wrote to encapsulate updating shadow from our device.

I have marked 2 lines in our code.

The issue is : when **new_json** is sent as  **{"state":{"reported":{"trigger":1}}}**
The 1st line shows the logger as 
Jun 10 19:47:31 D16 device_agent: update_digital_twin:Shadow update request {"state":{"reported":{"trigger":1}}}
**Which is correct**

But the 2nd  line shows logger as 
Jun 10 19:47:31 D16 device_agent: update_digital_twin:UpdateShadowRequest {"state":{}}
**This is incorrect.
Seems our understanding of how to construct UpdateShadowRequest.State from a valid json string for reported or desired state of shadow is not correct. PLEASE HELP ...** 

```
int CAwsSdkInterface::update_digital_twin(string new_json) {
	**1st line** spdlog::debug("update_digital_twin:Shadow update request {0}" , new_json);
	if (new_json.empty()) { 
		return FAILURE_UPDATE_EMPTY_STRING; 
	}
	JsonObject doc(new_json.c_str());
	if (!doc.WasParseSuccessful()) { 
		spdlog::error("Failed to parse json");
		return FAILURE_UPDATE_JSON_PARSE; 
	}
	std::condition_variable conditionPub;
	std::atomic<bool> updateSuccess(false);
	std::atomic<bool> updateFailed(false);
	
	std::mutex shadow_response_mutex;

	int rc = get_connection();
	if (rc != SUCCESS) { return rc; }

	UpdateShadowRequest request;
	request.ThingName = thingName.c_str();
	request.State = std::move(doc);
	//So far handleAccept or handleReject has not come into play till agent calls PublishUpdateShadow
	auto onPubAck = [&](int ioErr) {
		{
			std::unique_lock<std::mutex> lock(shadow_response_mutex);
			if (AWS_OP_SUCCESS == ioErr) {
				spdlog::debug("Shadow Update success");
				updateSuccess = true;
			}
			else {
				spdlog::debug("Shadow Update failed with error {0}", ioErr);
				updateFailed = true;
			}
		}
		conditionPub.notify_one();
	};

	// publishing request.State to this shadow/update topic
	// $aws/things/thingName/shadow/update
	{
		std::unique_lock<std::mutex> lock(shadow_response_mutex);
		spdlog::debug("PublishUpdateShadow");
		JsonObject doc2;
		request.SerializeToObject(doc2);
		**2nd line** spdlog::debug("update_digital_twin:UpdateShadowRequest {0}", doc2.View().WriteReadable().c_str());
		//todo : Possible optimization to allow callbacks instead of locks
		bool v3 = p_shadow_client->PublishUpdateShadow(request, pubSubQos, std::move(onPubAck));
		if (!v3) {
			spdlog::error("Failed to update shadow");
			return FAILURE_UPDATE_ACK_SUBSCRIBE;
		}
		//Initial publish
		conditionPub.wait(lock, [&]() {
			return updateSuccess.load() || updateFailed.load();
		});
		spdlog::debug("PublishUpdateShadow completed");
	}
	return (updateSuccess)? SUCCESS : FAILURE;
}
```

**Comment by ravichandhraRean** [comment]
@amitguptaRean 

If you change your publish message from **{"state":{"reported":{"trigger":1}}}**  to **{"reported":{"trigger":1}}**  the issue will be resolved.

Thank you.

**Comment by amitguptaRean** [comment]
Yes Ravi, this works.
[15:43:08:481280660: +00:00] [---D---] [thread 16206] update_digital_twin:Shadow update request {"reported":{"trigger":1}}
[15:43:08:481424907: +00:00] [---D---] [thread 16206] PublishUpdateShadow
[15:43:08:481589112: +00:00] [---D---] [thread 16206] update_digital_twin:UpdateShadowRequest {
        "state":        {
                "reported":     {
                        "trigger":      1
                }
        }
}

**Comment by ravichandhraRean** [comment]
@amitguptaRean solution provided by @JonathanHenson in #30

**Comment by ravichandhraRean** [comment]
@amitguptaRean 

Hi Amit,

We can close this and solution provided in #30 , it is working now.

Thank you.
