### ISSUE TITLE
An example for simple pub-sub communication?

### ISSUE THREAD

**Issue by David-Haim** [awslabs/aws-iot-device-sdk-cpp-v2#44]
Hello there.
I was told that the pub-sub functionality in this version of the AWS-IOT SDK is implemented. 

From what I see, only  device-shadow and jobs are given examples.

Where can I find an example of a simple pub-sub mechanism? will one be added eventually?

**Comment by ravichandhraRean** [comment]
Hi @David-Haim ,

Pub-Sub sample: https://github.com/awslabs/aws-crt-cpp/tree/master/samples/mqtt_pub_sub

once you build the aws-crt-cpp as mentioned in aws-iot-device-sdk-cpp-v2 the pub-sub sample will be there in your aws-crt-cpp build folder ready to use.
```
git clone --branch v0.4.1 https://github.com/awslabs/aws-crt-cpp.git
git clone https://github.com/awslabs/aws-iot-device-sdk-cpp-v2.git
mkdir aws-crt-cpp-build
cd aws-crt-cpp-build
cmake -DCMAKE_INSTALL_PREFIX="<path to where you install>" -DCMAKE_PREFIX_PATH="<path to where you install>" -DBUILD_SHARED_LIBS=ON -DBUILD_DEPS=ON ../aws-crt-cpp
cmake --build . --target install
cd ..
mkdir aws-iot-device-sdk-cpp-v2-build
cd aws-iot-device-sdk-cpp-v2-build
cmake -DCMAKE_INSTALL_PREFIX="<path to where you install>" -DCMAKE_PREFIX_PATH="<path to where you install>" -DBUILD_SHARED_LIBS=ON ../aws-iot-device-sdk-cpp-v2
cmake --build . --target install
```
Thank you.

Regards,
Ravichandhra Palla.

**Comment by David-Haim** [comment]
I see, thanks!

new problem: I can't build that sample :)

first problem: cmake complains there is no valid `cmake_minimum_required` - I added one.
second problem: cmake complains that the line `set_target_properties(${PUB_SUB_PROJECT_NAME} PROPERTIES CXX_STANDARD ${CMAKE_CXX_STANDARD})` has too many arguments - I commented it out

lastly, make complains that it can't find `aws_mem_acquire`

[ 50%] Linking CXX executable aws-crt-cpp-mqtt-pub-sub
/usr/bin/ld: CMakeFiles/aws-crt-cpp-mqtt-pub-sub.dir/main.cpp.o: undefined reference to symbol 'aws_mem_acquire'
//usr/local/lib/libaws-c-common.so.0unstable: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/aws-crt-cpp-mqtt-pub-sub.dir/build.make:94: recipe for target 'aws-crt-cpp-mqtt-pub-sub' failed
make[2]: *** [aws-crt-cpp-mqtt-pub-sub] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/aws-crt-cpp-mqtt-pub-sub.dir/all' failed
make[1]: *** [CMakeFiles/aws-crt-cpp-mqtt-pub-sub.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JonathanHenson** [comment]
This sample builds as part of the aws-crt-cpp build. It’s not going to build as a stand-alone project. After building the crt, the built sample is in your build directory.

**Comment by David-Haim** [comment]
Hi guys, what's up?

A little clarification is needed: in this example of pub-sub, can we use IOT things and their properties/certs ? 

I went to the IOT console, made a new thing, created certificates for it and copied the REST endpoint for the created thing. the example can't work with those parameters:

```
./aws-crt-cpp-mqtt-pub-sub --endpoint a73c5uwwia0zy-ats.iot.us-east-1.amazonaws.com --cert ./certs/4547a1a832-certificate.pem.crt --key ./certs/4547a1a832-public.pem.key --topic topeek --ca_file ./certs/AmazonRootCA1.pem
Client Configuration initialization failed with error aws-c-io: AWS_IO_TLS_CTX_ERROR, Failed to create tls context
```

any help?

**Comment by ravichandhraRean** [comment]
Hi @David-Haim ,

**A little clarification is needed: in this example of pub-sub, can we use IOT things and their properties/certs ?**

**Ans:** yes you can use them with the mqtt_pub_sub sample.

Your connection failing because you are using public key --key ./certs/4547a1a832-public.pem.key  instead of private key. Please use your private key file .

If still failing try to give full paths to your all certs.

Thank you.

**Comment by David-Haim** [comment]
I got it working, thanks :)

**Comment by jercylew** [comment]
Hi David, I have the same issue, I've provided correct private key, ca file and certificate but still get AWS_IO_TLS_CTX_ERROR error, can you tell me how to fix that, thanks a lot.

**Comment by donhpham** [comment]
Hello, I am able to get the example pub sub running successfully but I do have a question regarding multi-threaded support.

Is there an example to handle multiple threads? Specifically, I would like to call Publish from a separate thread. Thanks.

**Comment by bretambrose** [comment]
Nothing special needs to be done for multiple threads; publishes are thread-safe.

**Comment by rathnamachary** [comment]
Hi Team,
Iam able to run device advisor test suite with pub-sub test case and its passing with warnings.

regarding for the FOUND_UNSUPPORTED_CIPHER_SUITE warning:

How do we change the cipher suites and where do we change?
please provide the required steps to resolve the warning.

I tried below steps in ubuntu,
1) in the file,
/etc/apache2/sites-enabled/000-default.conf and 
/etc/apache2/mods-available/ssl.conf,
i have added:
SSLProtocol -all +TLSv1.3
and,
2)in the file,
/etc/ssl/openssl.cnf,
i have added:
openssl_conf = default_conf
[default_conf]
ssl_conf = ssl_sect
[ssl_sect]
system_default = system_default_sect
[system_default_sect]
MinProtocol = TLSv1.3
#CipherString = DEFAULT:@SECLEVEL=2
CipherString = ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384
Ciphersuites = TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256

but no luck.

Is it correct or anything missing?
