### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Kevin-Tacheny** [awslabs/aws-iot-device-sdk-cpp-v2#45]
Fail to build from scratch.

In file included from /home/kevin/aws_test_build/install/include/aws/crt/Types.h:17:0,
                 from /home/kevin/aws_test_build/install/include/aws/crt/Api.h:16,
                 from /home/kevin/aws_test_build/aws-iot-device-sdk-cpp-v2/samples/jobs/describe_job_execution/main.cpp:15:
/home/kevin/aws_test_build/install/include/aws/crt/Optional.h: In instantiation of ‘Aws::Crt::Optional<T>& Aws::Crt::Optional<T>::operator=(U&&) [with U = Aws::Crt::UUID; T = std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Crt::StlAllocator<char> >]’:
/home/kevin/aws_test_build/aws-iot-device-sdk-cpp-v2/samples/jobs/describe_job_execution/main.cpp:288:49:   required from here
/home/kevin/aws_test_build/install/include/aws/crt/Optional.h:59:30: error: ambiguous overload for ‘operator=’ (operand types are ‘std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Crt::StlAllocator<char> >’ and ‘Aws::Crt::UUID’)
                     *m_value = std::forward<U>(u);
                              ^
In file included from /usr/include/c++/5/string:52:0,
                 from /usr/include/c++/5/stdexcept:39,
                 from /usr/include/c++/5/array:38,
                 from /usr/include/c++/5/tuple:39,
                 from /usr/include/c++/5/functional:55,
                 from /usr/include/c++/5/memory:79,
                 from /home/kevin/aws_test_build/install/include/aws/crt/StlAllocator.h:17,
                 from /home/kevin/aws_test_build/install/include/aws/crt/Types.h:18,
                 from /home/kevin/aws_test_build/install/include/aws/crt/Api.h:16,
                 from /home/kevin/aws_test_build/aws-iot-device-sdk-cpp-v2/samples/jobs/describe_job_execution/main.cpp:15:
/usr/include/c++/5/bits/basic_string.h:550:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator=(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = Aws::Crt::StlAllocator<char>]
       operator=(const basic_string& __str)
       ^
/usr/include/c++/5/bits/basic_string.h:569:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator=(_CharT) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = Aws::Crt::StlAllocator<char>]
       operator=(_CharT __c)
       ^
/usr/include/c++/5/bits/basic_string.h:587:7: note: candidate: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator=(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = Aws::Crt::StlAllocator<char>]
       operator=(basic_string&& __str)
       ^
samples/jobs/describe_job_execution/CMakeFiles/describe-job-execution.dir/build.make:62: recipe for target 'samples/jobs/describe_job_execution/CMakeFiles/describe-job-execution.dir/main.cpp.o' failed
make[2]: *** [samples/jobs/describe_job_execution/CMakeFiles/describe-job-execution.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:250: recipe for target 'samples/jobs/describe_job_execution/CMakeFiles/describe-job-execution.dir/all' failed
make[1]: *** [samples/jobs/describe_job_execution/CMakeFiles/describe-job-execution.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by amitguptaRean** [comment]
shadow_sync sample is failing to compile as well

**Comment by JonathanHenson** [comment]
I’m working on getting some fixes out. In the meantime, can you give the update_deps branch of the crt a try?

**Comment by JonathanHenson** [comment]
Actually that’s gonna break green grass discovery. I’m working on getting all of these fixed back up.

**Comment by amitguptaRean** [comment]
No worries... in the meantime we commented out the code in samples, and build our agent to provide you the loggers today.

**Comment by ravichandhraRean** [comment]
Hi @JonathanHenson ,

Now building without any errors @Kevin-Tacheny @amitguptaRean 

Thank you.
