### ISSUE TITLE
Future support for connecting with access_key/secret_access_key

### ISSUE THREAD

**Issue by David-Haim** [awslabs/aws-iot-device-sdk-cpp-v2#48]
Hello there.

A small question: is there any plan to support connecting to the iot-servers using the access_key/secret_access_key?

Currently, I see only TLS certificates are supported in means of authentication. 

thanks!

**Comment by JonathanHenson** [comment]
Yes, the websocket support is in progress now. You can follow it on the aws-c-http, aws-c-auth, and aws-c-mqtt repos.

**Comment by David-Haim** [comment]
cool, I'll make sure to look it up in the future.
