### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by ravichandhraRean** [awslabs/aws-iot-device-sdk-cpp-v2#5]
Hi,

I am not able to build by following this given procedure in README.md
```
git clone --branch v0.1.1 https://github.com/awslabs/aws-crt-cpp.git
git clone https://github.com/awslabs/aws-iot-device-sdk-cpp-v2.git
mkdir aws-crt-cpp-build
cd aws-crt-cpp-build
cmake -DCMAKE_INSTALL_PREFIX="<path to where you install>" -DCMAKE_PREFIX_PATH="<path to where you install>" -DBUILD_SHARED_LIBS=ON -DBUILD_DEPS=ON ../aws-crt-cpp
<invoke build command make, msbuild, ninja etc....> install
cd ..
mkdir aws-iot-device-sdk-cpp-v2
cd aws-iot-device-sdk-cpp-v2
cmake -DCMAKE_INSTALL_PREFIX="<path to where you install>" -DCMAKE_PREFIX_PATH="<path to where you install>" -DBUILD_SHARED_LIBS=ON ../aws-iot-device-sdk-cpp-v2
<invoke build command make, msbuild, ninja etc....> install
```
There are two mistakes exists in the given procedure,
**1. (there is no v0.1.1 branch existed)**
`git clone --branch v0.1.1 https://github.com/awslabs/aws-crt-cpp.git  `

**2.   (I think it should be **aws-iot-device-sdk-cpp-v2-build**)**
```
 mkdir aws-iot-device-sdk-cpp-v2
 cd aws-iot-device-sdk-cpp-v2
```

I modified those two mistakes but not able build it successfully.

I couldn't understand what are these two **CMAKE_PREFIX_PATH , CMAKE_INSTALL_PREFIX** . It will be really helpful if you provide the description of those variables.

I tried to build it on Linux

Thank you.

Regards,
Ravichandhra Palla

**Comment by amitguptaRean** [comment]
AWS Team

All the issues raised by my colleague Ravi Chandhra above are valid concerns / mistakes
Once I followed the steps mentioned in his post, I am getting following failures when I try to build aws-iot-device-sdk-cpp-v2-build

We are doing a customer facing project and to avoid reworks took V2 SDK - ASSUMING by the time we hit production in 3-6 months, your SDK will be GA as well.

Regards
amit.gupta2@hitachivantara.com

================================================================
pi@raspberrypi:~/code-repos/aws-iot-device-sdk-cpp-v2-build $ cmake -DCMAKE_INSTALL_PREFIX=/home/pi/code-repos/libs -DCMAKE_PREFIX_PATH=/home/pi/code-repos/libs -DBUILD_SHARED_LIBS=ON ../aws-iot-device-sdk-cpp-v2
-- The CXX compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibCrypto: /usr/lib/arm-linux-gnueabihf/libcrypto.so  
-- Libcrypto Include Dir: /usr/include
-- Configuring done
CMake Error at jobs/CMakeLists.txt:42 (add_library):
  Target "IotJobs-cpp" links to target "AWS::aws-c-cal" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at shadow/CMakeLists.txt:42 (add_library):
  Target "IotShadow-cpp" links to target "AWS::aws-c-cal" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at samples/jobs/describe_job_execution/CMakeLists.txt:10 (add_executable):
  Target "describe-job-execution" links to target "AWS::aws-c-cal" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at samples/shadow/shadow_sync/CMakeLists.txt:10 (add_executable):
  Target "shadow-sync" links to target "AWS::aws-c-cal" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


-- Generating done
-- Build files have been written to: /home/pi/code-repos/aws-iot-device-sdk-cpp-v2-build

**Comment by amitguptaRean** [comment]
Fix for this -----
Add following to Line 18 aws-iot-device-sdk-cpp-v2/CMakeLists.txt
find_package(aws-c-cal REQUIRED)

**Comment by JonathanHenson** [comment]
thanks for bringing this to our attention, we'll get a fix out shortly

**Comment by JonathanHenson** [comment]
Also:

CMAKE_PREFIX_PATH is (where are any dependencies stored?)

CMAKE_INSTALL_PREFIX is (where do I put artifacts when you run make install)

**Comment by ravichandhraRean** [comment]
Hi @JonathanHenson 

after adding 
find_package(aws-c-cal REQUIRED)

the issue is fixed and now we are able to build the aws-crt-cpp, aws-iot-device-sdk-cpp-v2 and all samples using the CMAKE.

now we are able to understand CMAKE_PREFIX_PATH, CMAKE_INSTALL_PREFIX . Thank you.

thank you @amitguptaRean 

Regards,
Ravichandhra Palla
ravichandhra.palla@hitachivantara.com

**Comment by Kevin-Tacheny** [comment]
I can confirm that this is fixed in master from aws-crt-cpp
