### ISSUE TITLE
Unable to build on linux.

### ISSUE THREAD

**Issue by nkowdley** [awslabs/aws-iot-device-sdk-cpp-v2#52]
Following the instructions, I try to run the cmake command provided:
cmake -DCMAKE_INSTALL_PREFIX=~/.oelocal/x86_64 -DCMAKE_PREFIX_PATH=~/.oelocal/x86_64/ -DBUILD_SHARED_LIBS=ON -DBUILD_DEPS=ON ../aws-crt-cpp

This is the output I get
"""
CMake Error at CMakeLists.txt:26 (include):
  include could not find load file:
    AwsCFlags

CMake Error at CMakeLists.txt:27 (include):
  include could not find load file:
    AwsSharedLibSetup

CMake Error at CMakeLists.txt:28 (include):
  include could not find load file:
    AwsSanitizers

CMake Error at /usr/share/cmake-3.14/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
  By not providing "FindLibCrypto.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "LibCrypto", but CMake did not find one.
  Could not find a package configuration file provided by "LibCrypto" with
  any of the following names:
    LibCryptoConfig.cmake
    libcrypto-config.cmake

  Add the installation prefix of "LibCrypto" to CMAKE_PREFIX_PATH or set
  "LibCrypto_DIR" to a directory containing one of the above files.  If
  "LibCrypto" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /usr/lib64/s2n/cmake/s2n-config.cmake:3 (find_dependency)
  CMakeLists.txt:168 (find_package)

"""
Is there something I am missing from the instructions?

**Comment by nkowdley** [comment]
@JonathanHenson , I have OpenSSL 1.1.1c  installed on my computer.  I am running ArchLinux.  Here is the openssl package I have: https://www.archlinux.org/packages/core/x86_64/openssl/

I also have a file in /usr/lib/pkgconfig/libcrypto.pc 

Is there something I am missing?

**Comment by JonathanHenson** [comment]
Do you have the header files? Or just the lib?

**Comment by Kiddinglife** [comment]
@nkowdley I metame issueto . Just download opnssl src and compile them.

**Comment by MattCrist** [comment]
I'm also having this issue but I haven't been able to get around it.  Do you need to point the CMAKE_PREFIX_PATH to a certain directory for libcrypto?

**Comment by bretambrose** [comment]
If libcrypto and its headers are not in the standard system install location, you will need to set CMAKE_PREFIX_PATH to include a path that resolves to the appropriate install directory.  I know for development work, a lot of the team just installs everything (aws-c-* and s2n and openssl) into the same install root directory, which keeps CMAKE_PREFIX_PATH a single, simple path.

**Comment by MattCrist** [comment]
@bretambrose Thanks for the quick response.  I was able to get the iot library to build but when I try to build my application which references it, I again get a message that cmake cannot find libcrypto.  Any thoughts?

This is the message:
By not providing "FindLibCrypto.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "LibCrypto", but CMake did not find one.

  Could not find a package configuration file provided by "LibCrypto" with
  any of the following names:

    LibCryptoConfig.cmake
    libcrypto-config.cmake

  Add the installation prefix of "LibCrypto" to CMAKE_PREFIX_PATH or set
  "LibCrypto_DIR" to a directory containing one of the above files.  If
  "LibCrypto" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by bretambrose** [comment]
If you're following the build instructions in the readme, that cmake module gets installed into the overall install directory underneath lib/cmake

In particular, the line:

```cmake -DCMAKE_INSTALL_PREFIX="<path to where you install>"  -DBUILD_DEPS=ON ../aws-iot-device-sdk-cpp-v2```

controls where it will go.

Once you've found it you should be able to pass that install directory to cmake as the prefix path (or part of it) when building your own project.

**Comment by piliwilliam0306** [comment]
> @bretambrose Thanks for the quick response. I was able to get the iot library to build but when I try to build my application which references it, I again get a message that cmake cannot find libcrypto. Any thoughts?
> 
> This is the message:
> 
> ```
> By not providing "FindLibCrypto.cmake" in CMAKE_MODULE_PATH this project
> has asked CMake to find a package configuration file provided by
> "LibCrypto", but CMake did not find one.
> 
> Could not find a package configuration file provided by "LibCrypto" with
> any of the following names:
> 
> LibCryptoConfig.cmake
> libcrypto-config.cmake
> 
> Add the installation prefix of "LibCrypto" to CMAKE_PREFIX_PATH or set
> "LibCrypto_DIR" to a directory containing one of the above files.  If
> "LibCrypto" provides a separate development package or SDK, be sure it has
> been installed.
> ```

@MattCrist 
I got exactly the same error message when I try to build my application as well.
Did you figure what went wrong?
Thanks!

**Comment by jmklix** [comment]
Try using the following command:

`cmake -DCMAKE_INSTALL_PREFIX="<path to where you install>" -DBUILD_DEPS=ON -DBUILD_SHARED_LIBS=ON ../aws-iot-device-sdk-cpp-v2`

**Comment by piliwilliam0306** [comment]
> Try using the following command:
> 
> `cmake -DCMAKE_INSTALL_PREFIX="<path to where you install>" -DBUILD_DEPS=ON -DBUILD_SHARED_LIBS=ON ../aws-iot-device-sdk-cpp-v2`

@jmklix 
ya it worked,
Thanks a lot!
