### ISSUE TITLE
cmake related issue HttpRequestResponse.h Can't be found

### ISSUE THREAD

**Issue by MichaelGoberling** [awslabs/aws-iot-device-sdk-cpp-v2#57]
Operating System: Ubuntu 16.04

GCC: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)

Cmake: 3.5.1

I followed the **Build from Source** directions outlined in the README.md and came across this error after firing off the last step, `cmake --build . --target install`

`Scanning dependencies of target Discovery-cpp
[ 80%] Building CXX object discovery/CMakeFiles/Discovery-cpp.dir/source/GGGroup.cpp.o
[ 82%] Building CXX object discovery/CMakeFiles/Discovery-cpp.dir/source/DiscoveryClient.cpp.o
/home/user/aws/iot-sdk-v2/aws-iot-device-sdk-cpp-v2/discovery/source/DiscoveryClient.cpp:18:46: fatal error: aws/crt/http/HttpRequestResponse.h: No such file or directory
compilation terminated.
discovery/CMakeFiles/Discovery-cpp.dir/build.make:86: recipe for target 'discovery/CMakeFiles/Discovery-cpp.dir/source/DiscoveryClient.cpp.o' failed
make[2]: *** [discovery/CMakeFiles/Discovery-cpp.dir/source/DiscoveryClient.cpp.o] Error 1
CMakeFiles/Makefile2:195: recipe for target 'discovery/CMakeFiles/Discovery-cpp.dir/all' failed
make[1]: *** [discovery/CMakeFiles/Discovery-cpp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

This header file isn't found in the /include/ directories. Here's what I find after running cmake.

* /aws/iot-sdk-v2/build/include/aws/crt/http
* /aws/iot-sdk-v2/build/include/aws/crt/http/HttpConnectionManager.h
* /aws/iot-sdk-v2/build/include/aws/crt/http/HttpConnection.h
* /aws/iot-sdk-v2/build/include/aws/crt/http/HttpRequest.h
* /aws/iot-sdk-v2/aws-crt-cpp/include/aws/crt/http
* /aws/iot-sdk-v2/aws-crt-cpp/include/aws/crt/http/HttpConnectionManager.h
* /aws/iot-sdk-v2/aws-crt-cpp/include/aws/crt/http/HttpConnection.h
* /aws/iot-sdk-v2/aws-crt-cpp/include/aws/crt/http/HttpRequest.h

DiscoveryClient.cpp references a HttpClientConnectionOptions struct that I see in HttpConnection.h, so maybe that's the correct reference. Looks like the include was changed here https://github.com/awslabs/aws-iot-device-sdk-cpp-v2/pull/56. 

Otherwise, I can't figure this out, and if I've made an obvious error in attempting to build from source, any guidance would be greatly appreciated.

**Comment by justinboswell** [comment]
I will update the README, the version of aws-crt-cpp that you need for the latest version of this SDK is v0.5.3, so if you just do the clone/checkout of aws-crt-cpp with that version, you should be good to go.
