### ISSUE TITLE
When it will be Generally Available

### ISSUE THREAD

**Issue by ravichandhraRean** [awslabs/aws-iot-device-sdk-cpp-v2#6]
Hi,

We are planning to use this v2 SDK for our production code for greengrass, but before that we want to clarify these things,

1. Will this supports to connect to greengrass core?

2. When it will be Published as generally available (we are assuming with in next 3 months)?

3. Are you suggest us to use this for production?

We are eagerly waiting for your response.

Thank you.

Regards,
Ravichandhra Palla

**Comment by JonathanHenson** [comment]
We're currently finishing up our http implementation. Greengrass support will follow shortly after.

We can't really make a promise on an exact GA date, but we're aiming for some time this summer.

The answer to #3 really depends on the features you plan on using. I can give more info based on that.

When are you hoping to ship?

**Comment by amitguptaRean** [comment]
@JonathanHenson - We are planning to deliver the product around end of April

**Comment by JonathanHenson** [comment]
Rather than discussing this here. Could we jump on a call? Email me henso@amazon.com

**Comment by David-Haim** [comment]
Hi guys!
great work developing the next generation of AWS-IOT C++ SDK.
when is the pub/sub functionality planned to be added?

**Comment by JonathanHenson** [comment]
It already is. You just need an Mqtt client, see the samples to get one, the. You can do pubsub on that directly.

**Comment by David-Haim** [comment]
Cool, thanks!

**Comment by certabitmh** [comment]
Is release 0.1.1 already more stable than v1?
Having trouble with v1: doesn‘t detect broken subscription to shadow topics which leads to unreachable endpoint devices...

**Comment by mialo5** [comment]
I am also interested to know the progress of the cpp SDK v2. 

Do you have any idea when it will get released to General Availability as we are quite keen to use the latest version going forward. Also of all the SDK's that have been developed, is the C++ the better one to use from a security, performance and AWS effort perspective?

**Comment by JonathanHenson** [comment]
As far as progress goes, we’re working on http proxy support now in aws-c-http. You can follow us there to stay up to date. When that’s done and bound to the crt, we’ll be feature complete.

Assuming your second question is about the aws-iot-device-sdk-*-v2 packages:

They’ll all be basically the same from a perf and security standpoint. They’re all the same codebase underneath. So just pick the best language for your domain.
