### ISSUE TITLE
can you tell people the thread model used in this project?

### ISSUE THREAD

**Issue by Kiddinglife** [awslabs/aws-iot-device-sdk-cpp-v2#60]
how many thread?
what they do?
lock free ?
is it configurable to specify the number of thread？
thanks.

**Comment by bretambrose** [comment]
The v2 Iot SDKs are based on the aws common runtime.  In particular, the answers you want can all be found in the code and readme for [aws-c-io](https://github.com/awslabs/aws-c-io)

**Comment by JonathanHenson** [comment]
1. See EventLoopGroup
It defaults to a thread per logical CPU. However for most iot applications you probably only want 1, so just configure that if that’s what you want.
2. It’s a green threads model based on event loops and async io. Each thread can handle hundreds of connections depending on throughput.
3. Mostly, definitely in the hot path. There are places we have to move the caller into the correct thread and we use a combination of a mutex and eventfd to avoid the event loop from needing to take a lock.
4. Yes
