### ISSUE TITLE
Connection after discovery does not resume after connection loss

### ISSUE THREAD

**Issue by mialo5** [awslabs/aws-iot-device-sdk-cpp-v2#61]
I am currently using commit 42ec5c of the C++ v2. SDK with greengrass core v1.9.2. I am unable to use the latest SDK because the discovery does not work (i am waiting for a reply on the thread "Greengrass discovery sample appears to not be working after latest updates #53").

With regards to testing the AWS connection, i have run through some test cases and found that when the connection drops and then resumes, i get a segmentation fault.

So i get the following message printed out from the code in the connection->OnConnectionInterrupted function:
"Connection Interrupted with error libaws-c-common: AWS_ERROR_SUCCESS, Success.".
In most cases i get a segmentation fault directly after that message.

In one case i received the following also after the above message, and then the application aborted:
"Fatal error condition occurred in /tmp/aws_device_sdk/deps/aws-c-io/source/channel.c:261: channel->channel_state == AWS_CHANNEL_SHUT_DOWN".

I would like to provide more debug information by switching on the api logging (InitializeLogging) but that is only available in the newer versions of the SDK which doesnt work for me.

This is quite a concerning issue for our use case as the code should recover without the application crashing.

Any ideas on what is causing the fault and how to fix it?

**Comment by JonathanHenson** [comment]
We aren’t going to be able to support not at HEAD, how would we even advise you if you can’t update? On the greengrass issue, We need to track that down for you, but we aren’t able to reproduce at the moment.  Anyways it’s likely going to be trial and error to figure out what’s going on on your machine, you’ll need to update for us to be able to help.

**Comment by mialo5** [comment]
So i do realise that you aren't able to debug the non-master commit which is also my frustration at the moment. What i am asking is that, for the scenario relating to the connection dropping and then reconnecting there doesn't appear to be any code to handle this in your discovery sample (on the master). Should there be any cleanup or unsubscribing and has this specific scenario being tested i.e. does it work as desired?

On the thread that i referenced above relating to the discovery problems, i am using your sample directly without modifications and am still experiencing the errors. It may be related to an issue on my specific device but considering that i am using the same setup (as described in the thread) where legitimate bugs were identified i don't believe it is. Based on the error messages is there any assistance you can provide to solve this (what else would you require from me, as i am losing confidence in this as a solution)?

**Comment by JonathanHenson** [comment]
We’re trying to reproduce today. We’ll keep you posted

**Comment by mialo5** [comment]
Thanks.

We may have found a resolution to the first issue regarding the connection drop and reconnect.
